import Head from "next/head";
// import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={() => console.log("hello")}
        />
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((store) => (
            <Card
              key={store.id}
              name={store.name}
              imgUrl={store.imgUrl}
              href={`coffee-store/${store.id}`}
              className={styles.card}
            />
          ))}
        </div>
        <div className={styles.heroImage}>
          {/* <Image src="/static/hero-image.png" width={700} height={400} /> */}
        </div>
      </main>
    </div>
  );
}
